### ISSUE TITLE
java.lang.IllegalArgumentException: File must exist 	at com.alipay.sofa.ark.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:67)

### ISSUE THREAD

**Issue by yishe** [sofastack/sofa-ark#217]
### Describe the bug
springboot 项目 添加了依赖 
```
<dependency>
   <groupId>com.alipay.sofa</groupId>
    <artifactId>sofa-ark-springboot-starter</artifactId>
    <version>0.6.0</version>
</dependency>
```
 启动项目的时候 报空指针

原因可能是 我的maven仓库路径有空格，文件路径没有URLDecode，

报错
```
Caused by: java.lang.IllegalArgumentException: File must exist
	at com.alipay.sofa.ark.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:67)
	at com.alipay.sofa.ark.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:51)
	at com.alipay.sofa.ark.loader.jar.JarFile.<init>(JarFile.java:83)
	at com.alipay.sofa.ark.loader.archive.JarFileArchive.<init>(JarFileArchive.java:54)
	at com.alipay.sofa.ark.loader.archive.JarFileArchive.<init>(JarFileArchive.java:50)
	at com.alipay.sofa.ark.bootstrap.ClasspathLauncher$ClassPathArchive.getJarContainerArchive(ClasspathLauncher.java:118)
	at com.alipay.sofa.ark.bootstrap.ClasspathLauncher$ClassPathArchive.getContainerArchive(ClasspathLauncher.java:94)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.getContainerArchive(AbstractLauncher.java:120)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:59)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:77)
```

需要判断的地方

```
//com.alipay.sofa.ark.bootstrap.ClasspathLauncher.ClassPathArchive#getJarContainerArchive
protected ContainerArchive getJarContainerArchive() throws Exception {
	List<URL> urlList = this.filterUrls("com/alipay/sofa/ark/container/mark");
	if (urlList.isEmpty()) {
		return null;
	} else if (urlList.size() > 1) {
		throw new ArkRuntimeException("Duplicate Container Jar File Found.");
	} else {
		return new JarContainerArchive(new JarFileArchive(new File(((URL)urlList.get(0)).getFile())));
	}
}
```
((URL)urlList.get(0)).getFile() 这个路径 没有 URLDecode

### Environment

- SOFAArk version: 0.6.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): win10
- Maven version: 3.6.0
- IDE version: IDEA2018.01

**Comment by QilongZhang** [comment]
@yishe 是否能贴一下 ((URL)urlList.get(0)).getFile() 值？ 我测试了带空格的文件路径，是没有问题的

**Comment by yishe** [comment]
![question](https://user-images.githubusercontent.com/4452725/55146704-0b5fc400-5180-11e9-92d3-de93228bf92f.jpg)

**Comment by QilongZhang** [comment]
@yishe  好的，我这边拿 Windows 环境测试下，之前是在 Mac 测试的。

你那边分析有什么结论？ 确定是空格所致吗

**Comment by yishe** [comment]
```
public List<URL> filterUrls(String resource) throws Exception {
	List<URL> urlList = new ArrayList();
	Enumeration enumeration = this.urlClassLoader.findResources(resource);
	while(enumeration.hasMoreElements()) {
		URL resourceUrl = (URL)enumeration.nextElement();
		String resourceFile = resourceUrl.getFile();
		String jarFile = resourceFile.substring(0, resourceFile.length() - resource.length() - "!/".length());
		urlList.add(new URL(jarFile));
	}
	return urlList;
}
```
这里的resourceUrl.getFile() 方法返回的 路径有空格的话，会URLEncode，空格就是 %20 但是 new File(String) 却找不到对应的文件

**Comment by QilongZhang** [comment]
@yishe  get,  多谢反馈！
