### ISSUE TITLE
Javassist exception when using dubbo

### ISSUE THREAD

**Issue by imsunv** [sofastack/sofa-ark#280]
### Your question
use dubbo
```
com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:303)

Caused by: javassist.CannotCompileException: [source error] no such class: xx.service.Api
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:282)
	... 83 common frames omitted
Caused by: javassist.compiler.CompileError: no such class: xx.service.Api
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:468)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:319)
	at javassist.compiler.MemberResolver.resolveJvmClassName(MemberResolver.java:512)
	at javassist.compiler.MemberCodeGen.resolveClassName(MemberCodeGen.java:1145)
	at javassist.compiler.CodeGen.atDeclarator(CodeGen.java:712)
	at javassist.compiler.ast.Declarator.accept(Declarator.java:100)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at javassist.compiler.Javac.compileMethod(Javac.java:169)
	at javassist.compiler.Javac.compile(Javac.java:95)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
```
### Your scenes

- SOFAArk version: 0.6.0
- JVM version (e.g. `java -version`):  1.8
- OS version (e.g. `uname -a`): linux
- javassist-3.18.1-GA 
dubbo-2.6.2

似乎是从 plugin ClassLoader 去找Api 类，没有从context classloader

**Comment by imsunv** [comment]
The interface class is loaded by BizClassLoader, and the Wrapper class is loaded with PluginClassloader.
When creating a ClassPool, set the  Wrapper's cl for classpath , that is, the PluginClassloader causes the interface class to be found.
