### ISSUE TITLE
sofa.boot 3.1.3-->3.2.0  , sofa.ark  0.6.0--->1.0.0 ;  Static Merge Deployment, Startup Failure

### ISSUE THREAD

**Issue by airshiplay** [sofastack/sofa-ark#287]
`2019-09-10 13:14:11.560  INFO 25143 --- [       Thread-5] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.unDeploy(BizDeployServiceImpl.java:62)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.dispose(BizDeployServiceImpl.java:73)
        at com.alipay.sofa.ark.container.service.ArkServiceContainer.stop(ArkServiceContainer.java:142)
        at com.alipay.sofa.ark.container.ArkContainer.stop(ArkContainer.java:242)
        at com.alipay.sofa.ark.container.ArkContainer$1.run(ArkContainer.java:136)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.alipay.sofa.runtime.api.ServiceRuntimeException: java.lang.LinkageError: loader constraint violation: loader (instance of com/alipay/sofa/ark/container/service/classloader/PluginClassLoader) previously initiated loading for a different type with name "com/alipay/sofa/runtime/spi/spring/RuntimeShutdownAware"
        at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.shutdown(StandardSofaRuntimeManager.java:115)
        at com.alipay.sofa.runtime.SofaEventHandler.doUninstallBiz(SofaEventHandler.java:45)
        at com.alipay.sofa.runtime.SofaEventHandler.handleEvent(SofaEventHandler.java:35)
        at com.alipay.sofa.ark.container.service.event.EventAdminServiceImpl.sendEvent(EventAdminServiceImpl.java:71)
        at com.alipay.sofa.ark.container.model.BizModel.stop(BizModel.java:247)
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.unDeploy(DefaultBizDeployer.java:66)
        ... 6 more
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of com/alipay/sofa/ark/container/service/classloader/PluginClassLoader) previously initiated loading for a different type with name "com/alipay/sofa/runtime/spi/spring/RuntimeShutdownAware"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.resolveLocalClass(AbstractClasspathClassLoader.java:295)
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:98)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:67)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.shutdown(StandardSofaRuntimeManager.java:110)
        ... 11 more
`

**Comment by glmapper** [comment]
Are you using runtime-sofa-boot-plugin?

**Comment by LeagendaryHe** [comment]
我也在研究sofaark 加个好友探讨下啊 1143191737(QQ)

**Comment by glmapper** [comment]
runtime-sofa-boot-plugin has bean fixed, see [update runtime plugin upon 3.2.0 and above](https://github.com/sofastack/sofa-boot/issues/496).
