### ISSUE TITLE
The HttpServletRequest injected by the downstream service is empty when the service is called

### ISSUE THREAD

**Issue by Divernia** [sofastack/sofa-ark#337]
### Your question

现在我的测试环境中有两个Biz包（A依赖B）。A包中通过@SofaReference注入了B包的服务TestService。B包中TestService服务实现类中通过@Autowired注入了HttpServletRequest。但是在调用过程中服务实现类中的方法通过request对象获取不到前台传入的参数并抛出以下异常，请问有什么办法解决？

java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131)
	at org.springframework.web.context.support.WebApplicationContextUtils.currentRequestAttributes(WebApplicationContextUtils.java:312)
	at org.springframework.web.context.support.WebApplicationContextUtils.access$400(WebApplicationContextUtils.java:65)
	at org.springframework.web.context.support.WebApplicationContextUtils$RequestObjectFactory.getObject(WebApplicationContextUtils.java:328)
	at org.springframework.web.context.support.WebApplicationContextUtils$RequestObjectFactory.getObject(WebApplicationContextUtils.java:323)
	at org.springframework.beans.factory.support.AutowireUtils$ObjectFactoryDelegatingInvocationHandler.invoke(AutowireUtils.java:305)
	at com.sun.proxy.$Proxy98.getParameter(Unknown Source)

### Environment

- SOFAArk version: 0.6.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Win10
- Maven version: 3.5
- IDE version: STS4

**Comment by glmapper** [comment]
@Divernia 方便提供下 demo 工程吗

**Comment by Divernia** [comment]
> @Divernia 方便提供下 demo 工程吗

已发送至邮箱

**Comment by Divernia** [comment]
@glmapper 已发送至邮箱

**Comment by glmapper** [comment]
@Divernia 使用方式有些问题，HttpServletRequest 处理的是 web request ，你调用使用的是 sofa jvm 服务调用的，不是 web 请求

**Comment by Divernia** [comment]
@glmapper 嗯，了解，已经解决了，麻烦了
