### ISSUE TITLE
Questions about debugging the program under idea

### ISSUE THREAD

**Issue by wangwj** [sofastack/sofa-ark#360]
idea 在springboot的工程中 运行报错
通过debug发现问题大致如下，在初始化ark时，会将当前的工程作为一个biz进行初始化，结果会造成
springboot的入口代码那会执行二次，虽然是在不同的类加载器中初始化的（一个是app加载器，一个是biz加载器)，但是启动tomcat的时候会失败（原因是端口占用，启动两次肯定端口占用），通过我自己写的demo或我们example demo都是一样的问题，涉及到的代码
@SpringBootApplication  Springboot的入口程序会执行二次
public class StockMngApplication {

    public static void main(String[] args) {
        SpringApplication.run(StockMngApplication.class, args);
    }
}
SofaArkBootstrap 中的记录了biz的classname和method name，
 entryMethod = new EntryMethod(Thread.currentThread()); //会获取到上面的类和方法名，
在biz 初始化的时候再次执行
通过debug，真正的错误如下
org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:960)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatWebServer.addPreviouslyRemovedConnectors(ArkTomcatWebServer.java:255)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatWebServer.start(ArkTomcatWebServer.java:196)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.sofastack.stockmng.StockMngApplication.main(StockMngApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:228)
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:52)
	at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
	at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:46)
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:143)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:68)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:236)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1108)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:550)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:957)
	... 40 more

上面的错误吞掉了，控制台的错误如下：
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
11:45:29.995 ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: The host does not contain a Context
	at com.alipay.sofa.ark.springboot.web.ArkTomcatWebServer.findContext(ArkTomcatWebServer.java:145)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatWebServer.start(ArkTomcatWebServer.java:208)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.sofastack.stockmng.StockMngApplication.main(StockMngApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:228)
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:52)
	at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
	at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:46)
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:143)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:68)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:745)
11:45:30.001 INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
Exception in thread "main" java.lang.RuntimeException: Meet exception when determine whether to start SOFAArk!
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:49)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:30)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.sofastack.stockmng.StockMngApplication.main(StockMngApplication.java:16)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:59)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.startUpArk(ArkApplicationStartListener.java:55)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:41)
	... 11 more
Caused by: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.thread.IsolatedThreadGroup.rethrowUncaughtException(IsolatedThreadGroup.java:50)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:55)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:68)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:77)
	... 6 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.reflect.InvocationTargetException
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:81)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:143)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:104)
	... 14 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.reflect.InvocationTargetException
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:56)
	at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
	at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:46)
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:228)
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:52)
	... 19 more
Caused by: java.lang.IllegalStateException: The host does not contain a Context
	at com.alipay.sofa.ark.springboot.web.ArkTomcatWebServer.findContext(ArkTomcatWebServer.java:145)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatWebServer.start(ArkTomcatWebServer.java:208)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.sofastack.stockmng.StockMngApplication.main(StockMngApplication.java:16)

例子程序  https://github.com/wangwj/sofachannel-demo.git

**Comment by wangwj** [comment]
问题已经解决，原因是测试环境端口占用了，不过还是有一些疑问，问什么执行两次尔不存在问题呢

**Comment by glmapper** [comment]
> 问题已经解决，原因是测试环境端口占用了，不过还是有一些疑问，问什么执行两次尔不存在问题呢

看下你 ark 容器中有几个 biz 呢

**Comment by lylingzhen** [comment]
超过 3 个月未有回复的先自动关闭，有问题可以随时再开新的 Issues。另外，SOFAArk 2.0 已经采用原生 SpringBoot 启动方式，使用方式更加简化，兼容性更好。
