### ISSUE TITLE
sofaark failed to start

### ISSUE THREAD

**Issue by llzz9595** [sofastack/sofa-ark#374]
### Your question
sofaark启动失败

Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkBiz Loader] Startup In IDE:Mock version : can not load class: org.springframework.boot.actuate.endpoint.AbstractEndpoint
	at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:118)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:71)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

### Environment

- SOFAArk version:1.1.2
- JVM version (e.g. `java -version`):1.8
- OS: Ubuntu16.04
- demo: https://github.com/llzz9595/ark-demo.git

**Comment by glmapper** [comment]
@llzz9595 can provide more detailed information?

**Comment by terryJiangPeng** [comment]
试下加上spring-boot-starter-actuator的依赖

**Comment by lylingzhen** [comment]
Issues 超过 3 个月未有回复先关闭，麻烦提供更多的信息届时重开该 Issue 或提新的 Issue。
