### ISSUE TITLE
java.lang.RuntimeException: No SofaRuntimeManager Found!

### ISSUE THREAD

**Issue by spyvip** [sofastack/sofa-ark#387]
### Describe the bug

````
10:30:50.585 [main] INFO com.github.spy.apollo.sofa.ark.hostapp.Application - Started Application in 5.485 seconds (JVM running for 8.469)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:49)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.RuntimeException: No SofaRuntimeManager Found!
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:81)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:143)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:99)
        ... 8 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.RuntimeException: No SofaRuntimeManager Found!
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:56)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
        at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:46)
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
        ... 10 more
Caused by: java.lang.RuntimeException: No SofaRuntimeManager Found!
        at com.alipay.sofa.runtime.SofaBizHealthCheckEventHandler.getSofaRuntimeManager(SofaBizHealthCheckEventHandler.java:49)
        at com.alipay.sofa.runtime.SofaBizHealthCheckEventHandler.doHealthCheck(SofaBizHealthCheckEventHandler.java:37)
        at com.alipay.sofa.runtime.SofaBizHealthCheckEventHandler.handleEvent(SofaBizHealthCheckEventHandler.java:33)
        at com.alipay.sofa.runtime.SofaBizHealthCheckEventHandler.handleEvent(SofaBizHealthCheckEventHandler.java:29)
        at com.alipay.sofa.ark.container.service.event.EventAdminServiceImpl.sendEvent(EventAdminServiceImpl.java:74)
        at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:247)
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:52)
        ... 13 more

````

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
same as #388 , close it here.
