### ISSUE TITLE
No SofaRuntimeManager Found!

### ISSUE THREAD

**Issue by spyvip** [sofastack/sofa-ark#388]
### Describe the bug

![image](https://user-images.githubusercontent.com/1212932/89281336-842c3580-d67c-11ea-9e87-ec12bef79ec4.png)

示例工程
````
https://github.com/spyvip/sofa-ark-sample-all
````

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@spyvip 请参考 https://github.com/sofastack-guides/sofa-ark-dynamic-guides。

**Comment by glmapper** [comment]
all samples from kubecon sh， pls refrence to  https://github.com/sofastack-guides/sofa-ark-dynamic-guides

**Comment by jinkunaier** [comment]
@glmapper https://github.com/sofastack-guides/sofa-ark-dynamic-guides 升级到3.4.4版本依然报这个错误：
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.resolveLocalClass(AbstractClasspathClassLoader.java:302)
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:102)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:71)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.resolveExportClass(AbstractClasspathClassLoader.java:263)
        at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:93)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:71)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.alipay.sofa.boot.autoconfigure.runtime.SofaRuntimeAutoConfiguration.sofaRuntimeManager(SofaRuntimeAutoConfiguration.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 66 more
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkPlugin Loader] runtime-sofa-boot-plugin : can not load class: org.springframework.context.ApplicationContextAware
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:122)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:71)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 90 more
Exception in thread "Thread-0" com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.RuntimeException: No SofaRuntimeManager Found!
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.unDeploy(DefaultBizDeployer.java:70)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.unDeploy(BizDeployServiceImpl.java:62)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.dispose(BizDeployServiceImpl.java:73)
        at com.alipay.sofa.ark.container.service.ArkServiceContainer.stop(ArkServiceContainer.java:144)
        at com.alipay.sofa.ark.container.ArkContainer.stop(ArkContainer.java:242)
        at com.alipay.sofa.ark.container.ArkContainer$1.run(ArkContainer.java:136)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: No SofaRuntimeManager Found!
        at com.alipay.sofa.runtime.SofaBizUninstallEventHandler.getSofaRuntimeManager(SofaBizUninstallEventHandler.java:49)
        at com.alipay.sofa.runtime.SofaBizUninstallEventHandler.doUninstallBiz(SofaBizUninstallEventHandler.java:38)
        at com.alipay.sofa.runtime.SofaBizUninstallEventHandler.handleEvent(SofaBizUninstallEventHandler.java:33)
        at com.alipay.sofa.runtime.SofaBizUninstallEventHandler.handleEvent(SofaBizUninstallEventHandler.java:29)
        at com.alipay.sofa.ark.container.service.event.EventAdminServiceImpl.sendEvent(EventAdminServiceImpl.java:74)
        at com.alipay.sofa.ark.container.model.BizModel.stop(BizModel.java:275)
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.unDeploy(DefaultBizDeployer.java:66)
        ... 6 more
