### ISSUE TITLE
在JDK11中使用ark合并部署,出现NoClassDefFoundError

### ISSUE THREAD

**Issue by a413528002** [sofastack/sofa-ark#440]
### Your question
使用JDK11时出现NoClassDefFoundError: sun/misc/CompoundEnumeration

启动日志
10:09:17.728 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
10:09:17.743 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
10:09:17.827 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
10:09:17.827 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
10:09:17.861 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
10:09:17.862 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
10:09:17.945 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
10:09:17.952 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
10:09:17.953 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 11
10:09:17.958 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
10:09:17.961 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
10:09:17.964 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
10:09:17.974 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
        at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
        at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:272)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
        at io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:285)
        at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:156)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:138)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:138)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:88)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:83)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:64)
        at com.alipay.sofa.ark.container.session.NettyTelnetServer.<init>(NettyTelnetServer.java:59)
        at com.alipay.sofa.ark.container.session.StandardTelnetServerImpl.run(StandardTelnetServerImpl.java:88)
        at com.alipay.sofa.ark.container.session.StandardTelnetServerImpl.init(StandardTelnetServerImpl.java:114)
        at com.alipay.sofa.ark.container.service.ArkServiceContainer.start(ArkServiceContainer.java:87)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:141)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:99)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:49)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
10:09:17.980 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
10:09:17.985 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @3bf7ca37
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
        at java.base/java.lang.reflect.Method.invoke(Method.java:558)
        at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:334)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:325)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:272)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
        at io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:285)
        at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:156)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:138)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:138)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:88)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:83)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:64)
        at com.alipay.sofa.ark.container.session.NettyTelnetServer.<init>(NettyTelnetServer.java:59)
        at com.alipay.sofa.ark.container.session.StandardTelnetServerImpl.run(StandardTelnetServerImpl.java:88)
        at com.alipay.sofa.ark.container.session.StandardTelnetServerImpl.init(StandardTelnetServerImpl.java:114)
        at com.alipay.sofa.ark.container.service.ArkServiceContainer.start(ArkServiceContainer.java:87)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:141)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:99)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:49)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
10:09:18.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
10:09:18.020 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
10:09:18.023 [main] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 3995074560 bytes (maybe)
10:09:18.025 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\slim\AppData\Local\Temp (java.io.tmpdir)
10:09:18.025 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
10:09:18.035 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
10:09:18.053 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
10:09:18.061 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
10:09:18.062 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
10:09:18.122 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
10:09:18.908 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 25264 (auto-detected)
10:09:18.919 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
10:09:18.919 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
10:09:19.390 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
10:09:19.396 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
10:09:19.898 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 10:63:c8:ff:fe:63:05:ad (auto-detected)
10:09:19.971 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
10:09:19.971 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
10:09:20.131 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 16
10:09:20.131 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 16
10:09:20.137 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
10:09:20.142 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
10:09:20.143 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
10:09:20.144 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
10:09:20.146 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
10:09:20.147 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
10:09:20.153 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
10:09:20.160 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
10:09:20.169 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
10:09:20.171 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
10:09:20.172 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
10:09:20.221 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
10:09:20.222 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
10:09:20.228 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
10:09:20.304 [SOFA-ARK-telnet-server-worker-0-T1] INFO io.netty.handler.logging.LoggingHandler - [id: 0x57e02302] REGISTERED
10:09:20.316 [SOFA-ARK-telnet-server-worker-0-T1] INFO io.netty.handler.logging.LoggingHandler - [id: 0x57e02302] BIND: 0.0.0.0/0.0.0.0:1234
10:09:20.330 [SOFA-ARK-telnet-server-worker-0-T1] INFO io.netty.handler.logging.LoggingHandler - [id: 0x57e02302, L:/0:0:0:0:0:0:0:0:1234] ACTIVE
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:49)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: Pre find class com.alipay.sofa.runtime.ark.plugin.SofaRuntimeActivator occurs an error via plugin ClassLoaderHook: null.
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:81)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:143)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:99)
        ... 8 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: Pre find class com.alipay.sofa.runtime.ark.plugin.SofaRuntimeActivator occurs an error via plugin ClassLoaderHook: null.
        at com.alipay.sofa.ark.container.model.PluginModel.start(PluginModel.java:319)
        at com.alipay.sofa.ark.container.service.plugin.PluginDeployServiceImpl.deployPlugin(PluginDeployServiceImpl.java:61)
        at com.alipay.sofa.ark.container.service.plugin.PluginDeployServiceImpl.deploy(PluginDeployServiceImpl.java:49)
        at com.alipay.sofa.ark.container.pipeline.DeployPluginStage.process(DeployPluginStage.java:45)
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
        ... 10 more
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: Pre find class com.alipay.sofa.runtime.ark.plugin.SofaRuntimeActivator occurs an error via plugin ClassLoaderHook: null.
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.preLoadClass(PluginClassLoader.java:155)
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:92)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:71)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at com.alipay.sofa.ark.container.model.PluginModel.start(PluginModel.java:315)
        ... 14 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.NoClassDefFoundError: sun/misc/CompoundEnumeration
        at com.alipay.sofa.ark.container.service.extension.ExtensionLoaderServiceImpl.getExtensionContributor(ExtensionLoaderServiceImpl.java:96)
        at com.alipay.sofa.ark.container.service.extension.ExtensionLoaderServiceImpl.getExtensionContributorFromArkPlugin(ExtensionLoaderServiceImpl.java:66)
        at com.alipay.sofa.ark.spi.service.extension.ArkServiceLoader.loadExtensionFromArkPlugin(ArkServiceLoader.java:28)
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadPluginClassLoaderHook(PluginClassLoader.java:140)
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.preLoadClass(PluginClassLoader.java:151)
        ... 18 more
Caused by: java.lang.NoClassDefFoundError: sun/misc/CompoundEnumeration
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.getResourcesInternal(AbstractClasspathClassLoader.java:221)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.getResources(AbstractClasspathClassLoader.java:192)
        at com.alipay.sofa.ark.container.service.extension.ExtensionLoaderServiceImpl.loadExtension(ExtensionLoaderServiceImpl.java:117)
        at com.alipay.sofa.ark.container.service.extension.ExtensionLoaderServiceImpl.getExtensionContributor(ExtensionLoaderServiceImpl.java:85)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: sun.misc.CompoundEnumeration
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at com.alipay.sofa.ark.bootstrap.ContainerClassLoader.loadClass(ContainerClassLoader.java:42)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 26 more
10:09:22.191 [SOFA-ARK-telnet-server-worker-0-T1] INFO io.netty.handler.logging.LoggingHandler - [id: 0x57e02302, L:/0:0:0:0:0:0:0:0:1234] CLOSE

我应如何正确使用sofa-ark
### Environment

- SOFAArk version: 3.4.5
- JVM version (e.g. `java -version`): openjdk version "11" 2018-09-25
- OS version (e.g. `uname -a`):  win10
- Maven version: 3.6/3
- IDE version: 2020.1

**Comment by glmapper** [comment]
@a413528002 We have not tested compatibility for JDK8+ versions, it may be problematic. In addition, I noticed that you have used ClassLoaderHook. Could you please provide your case？

**Comment by Msimplehub** [comment]
jdk9与11移除了好多lib库，例如：sun.misc等，sofa-ark-container中用了misc中的lib，这种情况没法启动成功。
