### ISSUE TITLE
合并部署报c.ArkLoaderException an not load clas

### ISSUE THREAD

**Issue by it-linnan** [sofastack/sofa-ark#441]
### Your question

describe your question clearly

多个springboot项目合并部署 其中一个项目引用了sofatracer
启动时报错
```
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkBiz Loader] app-one:1.0.0 : can not load class: com.alipay.sofa.tracer.boot.datasource.processor.DataSourceBeanPostProcessor
        at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:113)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:67)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:275)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.getReturnType(OnBeanCondition.java:505)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanTypeForBeanMethod(OnBeanCondition.java:491)
        ... 40 more
Exception in thread "Thread-0" com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.IllegalArgumentException: BizState must be ACTIVATED, DEACTIVATED or BROKEN.
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.unDeploy(DefaultBizDeployer.java:70)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.unDeploy(BizDeployServiceImpl.java:62)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.dispose(BizDeployServiceImpl.java:73)
        at com.alipay.sofa.ark.container.service.ArkServiceContainer.stop(ArkServiceContainer.java:142)
        at com.alipay.sofa.ark.container.ArkContainer.stop(ArkContainer.java:242)
        at com.alipay.sofa.ark.container.ArkContainer$1.run(ArkContainer.java:136)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: BizState must be ACTIVATED, DEACTIVATED or BROKEN.
        at com.alipay.sofa.ark.common.util.AssertUtils.isTrue(AssertUtils.java:66)
        at com.alipay.sofa.ark.container.model.BizModel.stop(BizModel.java:239)
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.unDeploy(DefaultBizDeployer.java:66)
        ... 6 more
```

### Environment

- SOFAArk version:1.0.0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):windows10
- Maven version:3.6.3
- IDE version:intellij idea

**Comment by glmapper** [comment]
@it-linnan By  exception stacks ,maybe you should import tracer dependency to your module biz
