### ISSUE TITLE
ark plugin项目中log4j启动报错

### ISSUE THREAD

**Issue by q6413260** [sofastack/sofa-ark#451]
如下，发现只要再ark plugin项目中 使用log4j，启动ark包就一直报如下错

Caused by: java.util.ServiceConfigurationError: org.apache.logging.log4j.util.PropertySource: Provider org.apache.logging.log4j.util.EnvironmentPropertySource not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.<init>(PropertiesUtil.java:319)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.<init>(PropertiesUtil.java:310)
	at org.apache.logging.log4j.util.PropertiesUtil.<init>(PropertiesUtil.java:69)
	at org.apache.logging.log4j.util.PropertiesUtil.<clinit>(PropertiesUtil.java:49)
	at org.apache.logging.log4j.util.LoaderUtil.isIgnoreTccl(LoaderUtil.java:259)
	at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:162)
	at org.apache.logging.log4j.util.StackLocator.<clinit>(StackLocator.java:64)
	at org.apache.logging.log4j.util.StackLocatorUtil.<clinit>(StackLocatorUtil.java:28)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at com.sankuai.bcp.es.client7.TestClass7.<clinit>(TestClass7.java:14)
	at com.dianping.frog.aggregator.bootstrap.ExecuterJettyServer.main(ExecuterJettyServer.java:38)
	... 26 more

**Comment by glmapper** [comment]
@q6413260 maybe you should refer to https://github.com/sofastack/sofa-ark/tree/master/sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/log
