### ISSUE TITLE
集成skywalking启动失败

### ISSUE THREAD

**Issue by jessin20161124** [sofastack/sofa-ark#479]
### Describe the bug

集成skywalking启动失败

### Steps to reproduce
&nbsp;&nbsp;&nbsp;&nbsp;1. 命令：
  ```
  java  -javaagent:/Users/ruby/Downloads/agent/skywalking-agent.jar -Dserver.port=8081 -jar xxx-abc.jar
  ```

  &nbsp;&nbsp;&nbsp;&nbsp;2. 日志：
DEBUG 2022-03-23 15:41:33:654 main AgentPackagePath : The beacon class location is jar:file:/Users/ruby/Downloads/agent/skywalking-agent.jar!/org/apache/skywalking/apm/agent/core/boot/AgentPackagePath.class.
INFO 2022-03-23 15:41:33:656 main SnifferConfigInitializer : Config file found in /Users/ruby/Downloads/agent/config/agent.config.
  Exception in thread "main" java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
  at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
  at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:49)
  at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: java.lang.ExceptionInInitializerError
  at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
  at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
  at ch.qos.logback.classic.Logger.info(Logger.java:579)
  at com.alipay.sofa.ark.common.log.ArkLogger.info(ArkLogger.java:168)
  at com.alipay.sofa.ark.container.service.ArkServiceContainer.start(ArkServiceContainer.java:75)
  at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:141)
  at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:99)
  ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at ch.qos.logback.classic.spi.LoggingEvent.<clinit>(LoggingEvent.java)
  ... 15 more
Caused by: java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:137)
  ... 20 more
Caused by: java.lang.NoClassDefFoundError: Lorg/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/ConstructorInter;
             at java.lang.Class.getDeclaredFields0(Native Method)
             at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
             at java.lang.Class.getDeclaredField(Class.java:2068)
             at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:122)
             at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:192)
             at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3083)
             ... 25 more
Caused by: java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ConstructorInter
             at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
             at com.alipay.sofa.ark.bootstrap.ContainerClassLoader.loadClass(ContainerClassLoader.java:42)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
             ... 31 more

### Environment

- SOFAArk version:
1.1.0
- JVM version (e.g. `java -version`):
1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by yuanyuancin** [comment]
org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ConstructorInter is In dependence？

pls provide the jar for this

**Comment by xymak** [comment]
用 sofa-ark-guides 切换到 2.0.0-SNAPSHOT 和 1.1.0，都没有复现

**Comment by lylingzhen** [comment]
@jessin20161124 Hello，请问还有问题吗？按照 sofa-ark-guides demo 跑下来没有复现，先关闭，如果仍有问题，欢迎随时提问。
