### ISSUE TITLE
使用jdk11运行失败

### ISSUE THREAD

**Issue by Athlizo** [sofastack/sofa-ark#492]
### Describe the bug

`Caused by: java.lang.NoClassDefFoundError: sun/misc/CompoundEnumeration
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.getResourcesInternal(AbstractClasspathClassLoader.java:216)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.getResources(AbstractClasspathClassLoader.java:187)
        at com.alipay.sofa.ark.container.service.extension.ExtensionLoaderServiceImpl.loadExtension(ExtensionLoaderServiceImpl.java:152)
        at com.alipay.sofa.ark.container.service.extension.ExtensionLoaderServiceImpl.loadExtensionFromArkPlugin(ExtensionLoaderServiceImpl.java:134)
        at com.alipay.sofa.ark.container.service.extension.ExtensionLoaderServiceImpl.loadExtensionFromArkPlugins(ExtensionLoaderServiceImpl.java:126)
        at com.alipay.sofa.ark.container.service.extension.ExtensionLoaderServiceImpl.loadExtensionStartup(ExtensionLoaderServiceImpl.java:101)
        ... 23 more
Caused by: java.lang.ClassNotFoundException: sun.misc.CompoundEnumeration
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at com.alipay.sofa.ark.bootstrap.ContainerClassLoader.loadClass(ContainerClassLoader.java:42)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 29 more
`

jdk11已经把sun.misc.CompoundEnumeration移到java.lang.CompoundEnumeration

java.lang.CompoundEnumeration外部无法直接应用，目前的解决方案是复制一份sun.misc.CompoundEnumeration的代码并更改ark里面的引用

另外，jdk11打包的问题失败的问题我通过升级版本asm->7.0和maven.plugin->3.5 解决了

**Comment by lylingzhen** [comment]
@yuanyuancin  看一下？

**Comment by lylingzhen** [comment]
cc @lvjing2

**Comment by lylingzhen** [comment]
@gaosaroma Assign to you to track.

**Comment by Athlizo** [comment]
> @Athlizo 您好，能麻烦您描述一下您的使用场景及运行方式吗（或者贴一下demo）？以及使用的SOFAArk版本是多少呢？

使用ark的主要原因是想用到ark的动态部署jar包的能力，加快迭代效率。
为啥要纠结jdk11？原因是因为要用到的zgc


目前是基于ark 0.6.0上做的修改

看最新的master的代码还是没修复jdk11的运行问题吧
https://github.com/sofastack/sofa-ark/blob/a40692e1251f252763224a3b857c8974226e28a3/sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java 
第29行
jdk 11已经没有sun.misc.CompoundEnumeration这个类了

另外jdk11的classLoader的修改对 /actuator/bizState 的结果也是有影响的^_^

**Comment by gaosaroma** [comment]
sofa-ark supports jdk-11 now, so we close the issue. Recently, we will release a new version with supporting-jdk-11 feature.
