### ISSUE TITLE
starting Error

### ISSUE THREAD

**Issue by hejianzxl** [sofastack/sofa-ark#494]
### Your question
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.runtime.spi.component.SofaRuntimeManager]: Factory method 'sofaRuntimeManager' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)

Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkPlugin Loader] runtime-sofa-boot-plugin : can not load class: org.springframework.context.ApplicationContextAware
	at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:122)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:71)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version: 1.1.5
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version: 3
- IDE version:

**Comment by lylingzhen** [comment]
@yuanyuancin 这个是 Ark2.0 不支持 Plugin 的原因吗？

**Comment by yuanyuancin** [comment]
runtime-sofa-boot-plugin.jar中应该没有spring-context.jar，需要上传下实验demo

**Comment by lylingzhen** [comment]
@hejianzxl hello，麻烦上传一下实验 demo？

**Comment by l10178** [comment]
Mark

**Comment by hejianzxl** [comment]
好的，回头再测下，最近在忙其他事情。
