### ISSUE TITLE
【bug】start with java.lang.ClassNotFoundException: com.alipay.sofa.ark.web.embed.WebPluginActivator

### ISSUE THREAD

**Issue by zyclove** [sofastack/sofa-ark#596]
### Your question
java -jar -Denv=dev -Dproject.name=volcano-fat-app -Dsofa.ark.embed.enable=true  -Dcom.alipay.sofa.ark.master.b
iz=volcano-datasource   volcano-fat-app-starter/target/volcano-fat-app-executable-ark.jar 

Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.web.embed.WebPluginActivator

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/15028279/209903598-03bfbadb-de08-4e74-92ca-ecd9c9275847.png">

### Environment
 <sofa.boot.version>3.16.1</sofa.boot.version>
     <sofa.ark.version>2.0.8</sofa.ark.version>
        <sofa.tools.version>1.3.10</sofa.tools.version>
- SOFAArk version: 2.0.8
- JVM version (e.g. `java -version`):11
- OS version (e.g. `uname -a`):mac
- Maven version:3.6.3
- IDE version:2022.3

**Comment by zyclove** [comment]
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/15028279/209903878-d97fb1cc-f020-4d9a-9dc7-bc8f6f1517a6.png">
2:24:59.503 [SOFA-ARK-telnet-server-worker-0-T1] INFO io.netty.handler.logging.LoggingHandler - [id: 0x896ba361, L:/0:0:0:0:0:0:0:0:1234] ACTIVE
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:104)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:52)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.web.embed.WebPluginActivator
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:81)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:151)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:102)
        ... 8 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.web.embed.WebPluginActivator
        at com.alipay.sofa.ark.container.model.PluginModel.start(PluginModel.java:327)
        at com.alipay.sofa.ark.container.service.plugin.PluginDeployServiceImpl.deployPlugin(PluginDeployServiceImpl.java:61)
        at com.alipay.sofa.ark.container.service.plugin.PluginDeployServiceImpl.deploy(PluginDeployServiceImpl.java:49)
        at com.alipay.sofa.ark.container.pipeline.DeployPluginStage.process(DeployPluginStage.java:45)
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: com.alipay.sofa.ark.web.embed.WebPluginActivator
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at com.alipay.sofa.ark.bootstrap.ContainerClassLoader.loadClass(ContainerClassLoader.java:57)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.alipay.sofa.ark.container.model.PluginModel.start(PluginModel.java:323)
        ... 14 more

**Comment by zyclove** [comment]
Do you hava a wechat group or dingding?

**Comment by gaosaroma** [comment]
WebPluginActivator 属于 web-ark-plugin 插件，找不到类需要检查：执行的jar包（executable-ark）是否含有 web-ark-plugin 包；其次，web-ark-plugin 插件应该添加在宿主应用中，请检查 'executable-ark' 包是否为正常的宿主应用（普通 spring 应用的打包方式），spring boot web应用配置可参考：https://www.sofastack.tech/projects/sofa-boot/sofa-ark-spring-boot-demo/ 。

**Comment by lylingzhen** [comment]
DingDing: 24970018417
请问还有问题吗？

**Comment by lylingzhen** [comment]
@zyclove

**Comment by lylingzhen** [comment]
close this issue, please reopen if any
