### ISSUE TITLE
从2.0.3（ #548 ） 升级到2.0.4~2.1.1版本皆报错

### ISSUE THREAD

**Issue by HuangDayu** [sofastack/sofa-ark#610]
### 问题描述

最开始使用sofa-ark时是2.0.2版本，但是一直报错，后在钉钉群中 @有济 叫我使用master中的最新提交 #548  ，本地测试没有问题，一直沿用至今。

现在想升级到新的版本，但发现2.0.4 ~ 2.1.1的版本全部报同样的错误。

### 错误日志

master-biz启动成功后，调用ArkClient.installBiz(file)报此错误，用telnet控制台biz -i filepath 也报同样的错误。

BizInitializer类在master-biz中，ark-biz中是provided的。

```shell
2023-02-14 10:30:46,513 ERROR main                             - Install Biz: script-transform:1.0.0 fail,cost: 290 ms, started at: 10:30:46,221
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:287)
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:171)
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:150)
	at com.xxxx.service.impl.EdgeGatewayServiceImpl.installBiz(EdgeGatewayServiceImpl.java:40)
	at com.xxxx.service.StartUpService.installScriptTransform(StartUpService.java:104)
	at com.xxxx.service.StartUpService.startUp(StartUpService.java:87)
	at com.xxxx.config.AfterBizStartupEventHandler.handleEvent(AfterBizStartupEventHandler.java:57)
	at com.xxxx.config.AfterBizStartupEventHandler.handleEvent(AfterBizStartupEventHandler.java:31)
	at com.alipay.sofa.ark.container.service.event.EventAdminServiceImpl.sendEvent(EventAdminServiceImpl.java:74)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.sendEventAfterArkEmbedStartupFinish(ArkApplicationStartListener.java:103)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.startUpArkEmbed(ArkApplicationStartListener.java:97)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:53)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:39)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.xxxx.IotEdgeGatewayApplication.main(IotEdgeGatewayApplication.java:24)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.xxxx.script.transform.ScriptTransformApplication]; nested exception is java.io.FileNotFoundException: class path resource [com/xxxx/api/biz/BizInitializer.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.xxxx.script.transform.ScriptTransformApplication.main(ScriptTransformApplication.java:15)
	... 33 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [com/xxxx/api/biz/BizInitializer.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199)
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:696)
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getInterfaces(ConfigurationClassParser.java:1024)
	at org.springframework.context.annotation.ConfigurationClassParser.processInterfaces(ConfigurationClassParser.java:386)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:332)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:304)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175)
	... 46 common frames omitted
2023-02-14 10:30:46,566 ERROR main                             - UnInstall Biz: script-transform:1.0.0 fail.
````

- SOFAArk version: 2.0.3 #548 
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): win10
- Maven version: maven3
- IDE version: 2022.3.2

**Comment by lvjing2** [comment]
模块的 springframework 依赖是否也是 provided 的呢？

**Comment by lvjing2** [comment]
![image](https://user-images.githubusercontent.com/3754074/218665959-b0ec1080-7725-46ab-8bfb-d54313d4a8be.png)
 debug 看下，这里扫描类的时候路径是哪些？

**Comment by HuangDayu** [comment]
> 模块的 springframework 依赖是否也是 provided 的呢？

是provided的

**Comment by lvjing2** [comment]
> ![image](https://user-images.githubusercontent.com/3754074/218665959-b0ec1080-7725-46ab-8bfb-d54313d4a8be.png) debug 看下，这里扫描类的时候路径是哪些？

需要你再debug下，spring 和你的依赖都在基座里引入的话，是可以找到的，我们使用都是正常的，应该是你应用自身哪里有问题才导致的。

**Comment by HuangDayu** [comment]
类资源加载逻辑有bug，如果我的ark-biz中实现了master-biz的接口，这个接口类在biz的classloader中是不存在的，而是在主程序的classloader中。

正确的逻辑应该是，如果ark classloader非空，则从ark classloader中加载，如果inputstream还是null，则再从master classloader中加载，否则再抛出异常。 @lvjing2 

![1676429607642](https://user-images.githubusercontent.com/23421574/218915989-39dba83d-fac8-47ab-b97f-f4df1cda1f1d.png)

**Comment by HuangDayu** [comment]
`org.springframework.core.io.ClassPathResource` 类是在Spring-core的，我们用的Spring-boot的版本是2.7.0 @lvjing2

**Comment by HuangDayu** [comment]
我们是在sofa-ark的biz间集成了sofa-boot来实现ark-biz的JVM通讯的。但是，感觉sofa-boot并没有起来，看出logs路径下的error.log并没有错误日志。控制台中没有打印sofa-boot的版本，是不是意味着sofa-boot并没启动？

![image](https://user-images.githubusercontent.com/23421574/219013269-5dc64408-38d2-4092-928b-6c1c5824378b.png)

**Comment by HuangDayu** [comment]
@lvjing2 搞不明白的是，明明 #548 这个commit还是可以正常使用的，往后的版本都不行了，什么都没改，只是升级了sofa-ark的版本。

**Comment by penglinzhang** [comment]
> 

declaredMode 模式需要配合provided 一起使用吗：我没找到使用说明，

**Comment by lvjing2** [comment]
@penglinzhang 不是必须 provided，但是最佳实践推荐使用 provided，特别是中间件相关的依赖。declaredMode 原理说明，
#477 
#500 
使用说明可以看 READMe.md

**Comment by HuangDayu** [comment]
biz 中开启 declaredMode 模式，并且将依赖配置为 provided，依然此问题。 @lvjing2

**Comment by HuangDayu** [comment]
```shell
declaredMode 开启后，业务应用可以使用自己声明过的、且宿主应用拥有的通用依赖]
```

[文档链接](https://www.sofastack.tech/projects/sofa-boot/sofa-ark-spring-boot-demo/#:~:text=%E9%80%9A%E7%94%A8%E4%BE%9D%E8%B5%96%2D%2D%3E%0A%20%20%20%20%20%20%20%20%20%20%3C-,declaredMode,-%3Etrue%3C/)

从这个意思理解，我在master-biz中已经声明（compile）了该依赖（api模块），在ark-biz中也声明（provided）了该模块，并且实现了该api模块中的接口。这样做并无不妥吧？？？ 在 #548 中可以正常使用，往后的版本都不行了！

可否讲述一下， #548 之后的版本都做了什么设计上的改动，从而引发了这个问题。

**Comment by lvjing2** [comment]
> 类资源加载逻辑有bug，如果我的ark-biz中实现了master-biz的接口，这个接口类在biz的classloader中是不存在的，而是在主程序的classloader中。
> 
> 正确的逻辑应该是，如果ark classloader非空，则从ark classloader中加载，如果inputstream还是null，则再从master classloader中加载，否则再抛出异常。 @lvjing2
> 
> ![1676429607642](https://user-images.githubusercontent.com/23421574/218915989-39dba83d-fac8-47ab-b97f-f4df1cda1f1d.png)


这里只能说明模块里确实没有这个类，这个类是基座的还是模块的，基座的类的话，麻烦debug 看下这段代码
com.alipay.sofa.ark.container.model.BizModel#isDeclared()
这段代码，会拿到基座里扫描到的 jar 的artifactId，然后从模块的声明列表里做匹配，如果匹配不到，会出现你说的情况。

**Comment by HuangDayu** [comment]
实测2.1.2版本，有了新的问题，调用ArkClient.installBiz(file)安装biz，解压出来的源码包和application.yml 不翼而飞 ，导致启动失败。 @lvjing2 

![61dbf7b1c4bca1634778b4c7a64b582](https://user-images.githubusercontent.com/23421574/223905364-99378cb6-6132-4594-889a-8d138ea52578.png)

**Comment by HuangDayu** [comment]
我手动解压了jar，启动后com文件夹和application.yml 也不翼而飞，疑似sofa-ark被删除。

**Comment by lvjing2** [comment]
还能有这种事 😂，不应该的，可能是你本地电脑杀毒软件的操作。

**Comment by HuangDayu** [comment]
@lvjing2 看了杀毒软件（火绒、奇安信）都没有删除记录，应该不是杀毒软件的问题，而且没升级到2.1.2之前还可以正常使用的 🐶

**Comment by HuangDayu** [comment]
![image](https://user-images.githubusercontent.com/23421574/223939106-952d1c45-abba-4cfd-8122-72eff2b1869a.png)
![image](https://user-images.githubusercontent.com/23421574/223939228-67757a6b-2e91-47e0-abbd-a8fc6bfdc88f.png)

看，这是啥，或从诚不欺我。  @lvjing2  😅

**Comment by HuangDayu** [comment]
根本原因是因为 JarUtils.doGetArtifactIdFromJarPom(jarLocation) 扫描的jar路径是解压后的路径，所以 new JarFile(jarLocation) 异常，从而导致调用了Biz.stop()而删除了文件夹和配置文件。

![66497214fda3cd8f704c9eadc98c323](https://user-images.githubusercontent.com/23421574/224012367-6f754e7b-48ed-4665-b799-0891b2bc3e1d.png)

我正在debug，看是何原因导致jarLocation的值是解压后的路径。 @lvjing2

**Comment by HuangDayu** [comment]
![image](https://user-images.githubusercontent.com/23421574/224012702-eff7f3f4-2635-498e-9e4d-fce96a71893a.png)

stop函数中调用deleteQuietly会导致删除解压后的文件夹。

**Comment by HuangDayu** [comment]
我调用 ArkClient.installOperation 函数进行biz.jar安装，而不是ArkClient.installBiz() 就不会出现上述的 因jar被解压而加载jar包的异常的问题。然而，最先的classloader并没有解决。 @lvjing2 

![d96975ba9188d1e1724c46c5a2b8da1](https://user-images.githubusercontent.com/23421574/224027746-d096d2dd-8b2f-4c38-8176-8e35f935b219.png)

**Comment by HuangDayu** [comment]
同样的原因，biz classloader依然找不到该类。

![image](https://user-images.githubusercontent.com/23421574/224031016-beda2e6f-4d14-4cd1-8d8b-11d921cd40b6.png)

**Comment by lylingzhen** [comment]
这个 PR 已经合并了吗？

**Comment by HuangDayu** [comment]
已修改并覆盖单元测试
