### ISSUE TITLE
web-ark-plugin 中tomcat版本过低启动失败

### ISSUE THREAD

**Issue by gitYupan** [sofastack/sofa-ark#662]
- SOFA version:3.18.0
- SOFAArk version:2.1.3
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Darwin MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0
- Maven version:3.8.6
- IDE version:IntelliJ IDEA 2022.3.2

主工程启动报如下异常，大概看了下是web-ark-plugin-2.1.3.jar内置tomcat版本与springboot-2.7.10版本冲突

```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.web.embedded.TomcatWebServerFactoryCustomizer.lambda$customizeRejectIllegalHeader$24(TomcatWebServerFactoryCustomizer.java:228)

The following method did not exist:

    org.apache.coyote.http11.AbstractHttp11Protocol.setRejectIllegalHeader(Z)V

The calling method's class, org.springframework.boot.autoconfigure.web.embedded.TomcatWebServerFactoryCustomizer, was loaded from the following location:

    jar:file:/Users/***/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.7.10/spring-boot-autoconfigure-2.7.10.jar!/org/springframework/boot/autoconfigure/web/embedded/TomcatWebServerFactoryCustomizer.class

The called method's class, org.apache.coyote.http11.AbstractHttp11Protocol, is available from the following locations:

    jar:file:/Users/***/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.73/tomcat-embed-core-9.0.73.jar!/org/apache/coyote/http11/AbstractHttp11Protocol.class

The called method's class hierarchy was loaded from the following locations:

    org.apache.coyote.http11.AbstractHttp11Protocol: jar:file:/Users/***/.m2/repository/com/alipay/sofa/web-ark-plugin/2.1.3/web-ark-plugin-2.1.3.jar!/lib/tomcat-embed-core-9.0.12.jar!/
    org.apache.coyote.AbstractProtocol: jar:file:/Users/***/.m2/repository/com/alipay/sofa/web-ark-plugin/2.1.3/web-ark-plugin-2.1.3.jar!/lib/tomcat-embed-core-9.0.12.jar!/


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.autoconfigure.web.embedded.TomcatWebServerFactoryCustomizer and org.apache.coyote.http11.AbstractHttp11Protocol

16:17:51.318 [SOFA-ARK-telnet-server-worker-0-T1] INFO io.netty.handler.logging.LoggingHandler - [id: 0x7ab030c7, L:/0:0:0:0:0:0:0:0:1234] CLOSE
Exception in thread "main" java.lang.RuntimeException: Meet exception when determine whether to start SOFAArk!
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:66)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:39)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:79)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$starting$0(SpringApplicationRunListeners.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:56)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:298)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at com.hundsun.tbsp.ebs.gateway.EbsGatewayApplication.main(EbsGatewayApplication.java:19)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:60)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.startUpArk(ArkApplicationStartListener.java:72)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:58)
	... 14 more
Caused by: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.thread.IsolatedThreadGroup.rethrowUncaughtException(IsolatedThreadGroup.java:50)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:56)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:104)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:73)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:78)
	... 6 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.reflect.InvocationTargetException
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:81)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:152)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:113)
	... 14 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.reflect.InvocationTargetException
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:61)
	at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
	at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:47)
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:285)
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:57)
	... 19 more
Caused by: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.NoSuchMethodError: org.apache.coyote.http11.AbstractHttp11Protocol.setRejectIllegalHeader(Z)V
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at com.hundsun.tbsp.ebs.gateway.EbsGatewayApplication.main(EbsGatewayApplication.java:19)
	... 26 more
Caused by: java.lang.NoSuchMethodError: org.apache.coyote.http11.AbstractHttp11Protocol.setRejectIllegalHeader(Z)V
	at org.springframework.boot.autoconfigure.web.embedded.TomcatWebServerFactoryCustomizer.lambda$customizeRejectIllegalHeader$24(TomcatWebServerFactoryCustomizer.java:228)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.customizeConnector(TomcatServletWebServerFactory.java:348)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatServletWebServerFactory.initEmbedTomcat(ArkTomcatServletWebServerFactory.java:123)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatServletWebServerFactory.getWebServer(ArkTomcatServletWebServerFactory.java:90)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:184)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
	... 34 more
```

**Comment by lylingzhen** [comment]
@gaosaroma ark 2.0 还支持自带 tomcat 吗？

**Comment by gaosaroma** [comment]
@lylingzhen web-ark-plugin 自带了 spring-boot-starter-tomcat-2.1.0.RELEASE
