### ISSUE TITLE
采用基座静态执行数据库操作时，报错 object is not an instance of declaring class

### ISSUE THREAD

**Issue by hadoop835** [sofastack/sofa-ark#663]
### Describe the bug
spring-boot-ark-biz
### pom.xml
       <properties>
	        <java.version>8</java.version>
	        <sofa.ark.version>2.1.3</sofa.ark.version>
	        <druid.version>1.2.18</druid.version>
	        <mysql.version>5.1.49</mysql.version>
	        <mybatis-flex.version>1.3.5</mybatis-flex.version>
        </properties> 
	<dependency>
	        <groupId>com.alibaba</groupId>
	        <artifactId>druid-spring-boot-starter</artifactId>
	        <version>${druid.version}</version>
	        <scope>provided</scope>
        </dependency>
        <dependency>
	        <groupId>mysql</groupId>
	        <artifactId>mysql-connector-java</artifactId>
	        <version>${mysql.version}</version>
	        <scope>provided</scope>
        </dependency>
        <dependency>
	        <groupId>com.mybatis-flex</groupId>
	        <artifactId>mybatis-flex-spring-boot-starter</artifactId>
	        <version>${mybatis-flex.version}</version>
	        <scope>provided</scope>
        </dependency>

### 实体类：User
          @Table(value = "t_user")
          public class User implements Serializable {
              @Id(keyType = KeyType.Generator,value = "snowFlakeId")
              private Long id;
              private String userName;
              private String passWord;
              private String realName;
          
          
              public Long getId() {
                  return id;
              }
          
              public void setId(Long id) {
                  this.id = id;
              }
          
              public String getUserName() {
                  return userName;
              }
          
              public void setUserName(String userName) {
                  this.userName = userName;
              }
          
              public String getPassWord() {
                  return passWord;
              }
          
              public void setPassWord(String passWord) {
                  this.passWord = passWord;
              }
          
              public String getRealName() {
                  return realName;
              }
          
              public void setRealName(String realName) {
                  this.realName = realName;
              }
          }
### mapper
      public interface UserMapper extends BaseMapper<User>{
      
      }
###sofa-ark-spring-guides
### pom.xml
          <properties>
		<java.version>1.8</java.version>
		<sofa.ark.version>2.1.3</sofa.ark.version>
		<druid.version>1.2.18</druid.version>
		<mysql.version>5.1.49</mysql.version>
		<mybatis-flex.version>1.3.5</mybatis-flex.version>
	</properties>

		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-springboot-starter</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>web-ark-plugin</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-all</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-ark-api</artifactId>
			<version>${sofa.ark.version}</version>
		</dependency>

		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>spring-boot-ark-biz</artifactId>
			<version>0.0.2-SNAPSHOT</version>
			<classifier>ark-biz</classifier>
		</dependency>

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>druid-spring-boot-starter</artifactId>
			<version>${druid.version}</version>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>${mysql.version}</version>
		</dependency>
		<dependency>
			<groupId>com.mybatis-flex</groupId>
			<artifactId>mybatis-flex-spring-boot-starter</artifactId>
			<version>${mybatis-flex.version}</version>
		</dependency>

###
### 报错数据时报错
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:44) ~[mybatis-3.5.13.jar:3.5.13]
	at com.mybatisflex.core.keygen.CustomKeyGenerator.processBefore(CustomKeyGenerator.java:74) ~[mybatis-flex-core-1.3.5.jar:na]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.generateKeys(BaseStatementHandler.java:143) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:64) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:42) ~[mybatis-3.5.13.jar:3.5.13]
	at com.mybatisflex.core.mybatis.FlexPreparedStatementHandler.<init>(FlexPreparedStatementHandler.java:38) ~[mybatis-flex-core-1.3.5.jar:na]
	at com.mybatisflex.core.mybatis.FlexStatementHandler.<init>(FlexStatementHandler.java:59) ~[mybatis-flex-core-1.3.5.jar:na]
	at com.mybatisflex.core.mybatis.FlexConfiguration.newStatementHandler(FlexConfiguration.java:103) ~[mybatis-flex-core-1.3.5.jar:na]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184) ~[mybatis-3.5.13.jar:3.5.13]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425) ~[mybatis-spring-2.1.0.jar:2.1.0]
	at com.sun.proxy.$Proxy77.insert(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272) ~[mybatis-spring-2.1.0.jar:2.1.0]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:142) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86) ~[mybatis-3.5.13.jar:3.5.13]
	at com.sun.proxy.$Proxy88.insert(Unknown Source) ~[na:na]
	at com.mybatisflex.core.BaseMapper.insert(BaseMapper.java:46) ~[mybatis-flex-core-1.3.5.jar:na]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[na:1.8.0_162]
	at org.apache.ibatis.binding.MapperProxy$DefaultMethodInvoker.invoke(MapperProxy.java:155) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86) ~[mybatis-3.5.13.jar:3.5.13]
	at com.sun.proxy.$Proxy88.insert(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at com.mybatisflex.core.mybatis.MapperInvocationHandler.invoke(MapperInvocationHandler.java:74) ~[mybatis-flex-core-1.3.5.jar:na]
	at com.sun.proxy.$Proxy88.insert(Unknown Source) ~[na:na]
	at com.alipay.sofa.springbootarkbiz.service.impl.UserServiceImpl.save(UserServiceImpl.java:29) ~[spring-boot-ark-biz-0.0.2-SNAPSHOT-ark-biz.jar:0.0.2-SNAPSHOT]
	at com.alipay.sofa.springbootarkbiz.rest.SampleController.save(SampleController.java:22) ~[spring-boot-ark-biz-0.0.2-SNAPSHOT-ark-biz.jar:0.0.2-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.60.jar:9.0.60]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]

### Environment

- SOFAArk version: 2.1.3
- JVM version (e.g. `java -version`): 1.8.0_162
- OS version (e.g. `uname -a`):  windows
- Maven version: 
- IDE version: 2019.3.1

###  实例包
[sofa-ark-spring-guides.zip](https://github.com/sofastack/sofa-ark/files/11684846/sofa-ark-spring-guides.zip)
[spring-boot-ark-biz.zip](https://github.com/sofastack/sofa-ark/files/11684847/spring-boot-ark-biz.zip)
### sql脚本
      DROP TABLE IF EXISTS `t_user`;
      CREATE TABLE `t_user`  (
        `id` bigint(30) NOT NULL,
        `user_name` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
        `pass_word` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
        `real_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
        PRIMARY KEY (`id`) USING BTREE
      ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
      
      SET FOREIGN_KEY_CHECKS = 1;

**Comment by sususama** [comment]
我这边找不到您使用的这个依赖项
```xml
		<dependency>
			<groupId>com.mybatis-flex</groupId>
			<artifactId>mybatis-flex-spring-boot-starter</artifactId>
			<version>${mybatis-flex.version}</version>
		</dependency>
```
我将版本改成了1.3.1可以吗

**Comment by sususama** [comment]
我本地运行并没有出现您所描述的跑起来就会出现的问题

**Comment by sususama** [comment]
我这边debug到好像是您使用的mybatisflex的问题，这它到后面给ID好像丢了，我没仔细debug,
![1d8b03a80b459e5c910ebfab1698ef81](https://github.com/sofastack/sofa-ark/assets/52159774/50e81a10-12b9-4123-b009-ce736bd8a349)
，这个问题应该不是SOFA Ark的问题，它能找到对应的方法，而且报错也是非法数据

**Comment by hadoop835** [comment]
### maven 仓库存在
![image](https://github.com/sofastack/sofa-ark/assets/8055054/3fc11d90-fa4b-4817-ae56-548b6f944c1a)

### 验证方式
    访问地址：http://127.0.0.1:8080/biz/save
    提交方式：POST
    提交JSON: {"userName":"username","passWord":"123456","realName":"战神"}

### 报错在
![image](https://github.com/sofastack/sofa-ark/assets/8055054/920c757b-6635-4ac8-af0b-e2d0616c00cc)

### 单独运行服务
直接运行spring-boot-ark-biz没有问题
