### ISSUE TITLE
内嵌的tomcat是否可以升级下

### ISSUE THREAD

**Issue by sq1015** [sofastack/sofa-ark#684]
https://github.com/sofastack/sofa-ark/blob/9b57a546b9700eb3cfe8c2d4bdefe5e599d3ca1e/sofa-ark-plugin/web-ark-plugin/pom.xml#L16C4-L16C4

内嵌的tomcat是否可以升级下，与springboot(2.6.6版本)出现不兼容
Caused by: java.lang.NoSuchMethodError: org.apache.coyote.http11.AbstractHttp11Protocol.setRejectIllegalHeader(Z)V
	at org.springframework.boot.autoconfigure.web.embedded.TomcatWebServerFactoryCustomizer.lambda$customizeRejectIllegalHeader$24(TomcatWebServerFactoryCustomizer.java:209)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.customizeConnector(TomcatServletWebServerFactory.java:346)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatServletWebServerFactory.initEmbedTomcat(ArkTomcatServletWebServerFactory.java:123)
	at com.alipay.sofa.ark.springboot.web.ArkTomcatServletWebServerFactory.getWebServer(ArkTomcatServletWebServerFactory.java:90)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)

**Comment by sq1015** [comment]
重复问题
