### ISSUE TITLE
NoClassDefFoundError when java -jar

### ISSUE THREAD

**Issue by ochive** [sofastack/sofa-ark#903]
### Describe the question or bug

If ARK is not used for packaging, the project runs normally and runs after packaging.

It is normal to use ark to package the project's dependencies into ark plugins and to pack the project into ark packages.

Start the project directly using IDEA (without any VM parameters) and can be accessed normally.

But running the jar package directly results in an error:

```powershell
java "-Dsofa.ark.embed.enable=true" -jar ".\dataintegration-run-management-provider-1.0.0-SNAPSHOT-ark-executable.jar"
```

```text
 java "-Dsofa.ark.embed.enable=true" -jar ".\dataintegration-run-management-provider-1.0.0-SNAPSHOT-ark-executable.jar"
Exception in thread "main" java.lang.NoClassDefFoundError: com/alipay/sofa/ark/common/util/FileUtils
        at com.alipay.sofa.ark.bootstrap.BaseExecutableArchiveLauncher.createArchive(BaseExecutableArchiveLauncher.java:70)
        at com.alipay.sofa.ark.bootstrap.BaseExecutableArchiveLauncher.<init>(BaseExecutableArchiveLauncher.java:42)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.<init>(ArkLauncher.java:38)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: java.lang.ClassNotFoundException: com.alipay.sofa.ark.common.util.FileUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 4 more
```

### Pom.xml

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <!--打包可运行 mvn package spring-boot:repackage-->
            <plugin>
                <groupId>com.alipay.sofa</groupId>
                <artifactId>sofa-ark-maven-plugin</artifactId>
                <version>${sofa.ark.version}</version>
                <executions>
                    <execution>
                        <id>default-cli</id >
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

```xml
        <!--sofa boot-->
<!--        <dependency>-->
<!--            <groupId>com.alipay.sofa</groupId>-->
<!--            <artifactId>runtime-sofa-boot-starter</artifactId>-->
<!--            <version>${sofa.boot.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.alipay.sofa</groupId>-->
<!--            <artifactId>isle-sofa-boot-starter</artifactId>-->
<!--            <version>${sofa.boot.version}</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-springboot-starter</artifactId> <!-- spring boot 宿主应用的必要依赖-->
            <version>${sofa.ark.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-all</artifactId>
            <version>${sofa.ark.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-api</artifactId>
            <version>${sofa.ark.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>web-ark-plugin</artifactId>
            <version>${sofa.ark.version}</version>
        </dependency>
```

### Environment

- SOFAArk version:2.2.7
- JVM version : 17
- OS version : windows 10
- Maven version: 3.8.3
- IDE version: IDEA community 2023
- spring boot : 2.6.1

**Comment by ochive** [comment]
我再次仔细看了官方文档, 里面提到2.0版本以后, 直接使用springboot的maven打包插件即可.
```xml
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <outputDirectory>target</outputDirectory>
                    <classifier>ark-biz</classifier>
                </configuration>
                <executions>
                    <execution>
                        <id>package</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
打包后得到一个包"project-1.0.0-SNAPSHOT-ark-biz.jar",
以前打包时是生成三个包, "origin.jar", "origin-ark-biz.jar", "origin-ark-executable.jar".
直接使用java -jar运行"ark-biz.jar"包, 可以成功运行了.虽然有报错, 但应该是缺少几个JDK8包造成的.

**Comment by ochive** [comment]
我还是有一个问题, 文档里提到命令行运行或者IDEA运行都要携带参数:
```text
-Dsofa.ark.embed.enable=true -Dcom.alipay.sofa.ark.master.biz=${bizName}
```
但我没带参数,似乎也可运行, 请问带参数的作用是什么?

**Comment by lvjing2** [comment]
你好，是为了解决合并部署的问题吗？

**Comment by ochive** [comment]
你好,是这个地址中提到的:"https://www.sofastack.tech/projects/sofa-boot/sofa-ark-migration-guide/".
它提到sofa-ark升级到2.0后,不再需要使用原来的sofa-ark-maven-plugin插件了.

**Comment by ochive** [comment]
> > 我再次仔细看了官方文档, 里面提到2.0版本以后, 直接使用springboot的maven打包插件即可.
> > ```
> > <plugin>
> >                 <groupId>org.springframework.boot</groupId>
> >                 <artifactId>spring-boot-maven-plugin</artifactId>
> >                 <version>${spring-boot.version}</version>
> >                 <configuration>
> >                     <outputDirectory>target</outputDirectory>
> >                     <classifier>ark-biz</classifier>
> >                 </configuration>
> >                 <executions>
> >                     <execution>
> >                         <id>package</id>
> >                         <goals>
> >                             <goal>repackage</goal>
> >                         </goals>
> >                     </execution>
> >                 </executions>
> >             </plugin>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 打包后得到一个包"project-1.0.0-SNAPSHOT-ark-biz.jar", 以前打包时是生成三个包, "origin.jar", "origin-ark-biz.jar", "origin-ark-executable.jar". 直接使用java -jar运行"ark-biz.jar"包, 可以成功运行了.虽然有报错, 但应该是缺少几个JDK8包造成的.
> 
> 这个不对吧，是哪里的官网呢？

你好,是这个地址中提到的:"https://www.sofastack.tech/projects/sofa-boot/sofa-ark-migration-guide/".
```text
在SOFAArk1.0中使用sofa-ark-maven-plugin打包，在SOFAArk2.0中采用spring-boot原生打包插件spring-boot-maven-plugin打包
```

**Comment by ochive** [comment]
我目前已经解决我提到的问题了, 步骤如下: 

1. 统一sofa-ark版本为2.2.7 (3.X前的最后一个release版本)
2. 插件项目的依赖中仅将sofa-ark-plugin-maven-plugin的版本升级到2.2.7,其他不变
3. 主应用将sofa-boot从中移除, 因为我只需要类隔离功能.
4. 主应用引入sofa-ark的依赖.

```xml
<dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-springboot-starter</artifactId> <!-- spring boot 宿主应用的必要依赖-->
            <version>${sofa.ark.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-all</artifactId>
            <version>${sofa.ark.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-api</artifactId>
            <version>${sofa.ark.version}</version>
        </dependency>
```

5. 主应用配置打包插件

```xml
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <outputDirectory>target</outputDirectory>
                    <classifier>ark-biz</classifier>
                </configuration>
                <executions>
                    <execution>
                        <id>package</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

6. maven重新编译打包
7. jar -jar执行, 无论是否携带"-Dsofa.ark.embed.enable=true -Dcom.alipay.sofa.ark.master.biz=${bizName}"这两VM参数, 都启动成功.但是为了安全起见,我还是带了.
8. 其他一些报错, 可能是因为sofa-ark依赖jdk8的一些sun包, 我引入一些sun的pollyfill包后解决了, 比如"jdk.tools-jdk.tools","com.sun-tools".

**Comment by lvjing2** [comment]
你是使用多应用合并部署能力吗？不参考下 https://github.com/koupleless/samples 这个吗？这个是使用 SOFAArk 做的模块化研发框架与平台能力。

**Comment by lvjing2** [comment]
Hi, 你的问题解决了吗？

**Comment by ochive** [comment]
@lvjing2 你好,主要是因为这是一个存量项目, 由于它有大量插件项目(各自依赖各种冲突), 因此使用了ark.
我对此项目了解有限, 因此目前能解决多依赖的隔离就可以了.
已经解决了, 谢谢!
